# Generated by Django 5.2.6 on 2025-09-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_varicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varicao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
