# Generated by Django 5.2.6 on 2025-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
