# Generated by Django 5.2.6 on 2025-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao_id',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.PositiveIntegerField(),
        ),
    ]
