# Generated by Django 5.2.6 on 2025-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_itempedido_variacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.CharField(max_length=255),
        ),
    ]
